---
version: 2
project_name: chart-releaser

env:
  - COSIGN_YES=true

before:
  hooks:
    - go mod download

sboms:
  - artifacts: archive

builds:
  - main: cr/main.go
    binary: cr
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    ldflags:
      - >-
        -X github.com/helm/chart-releaser/cr/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-releaser/cr/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-releaser/cr/cmd.BuildDate={{ .Date }}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

signs:
  - id: all
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: all