name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: ./go.mod
          check-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          install-only: true

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Install syft
        uses: anchore/sbom-action/download-syft@v0.17.2

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: chainguard-dev/actions/goimports@main

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          args: -v release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
